# Generated by Django 5.1.2 on 2024-10-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
