# Generated by Django 5.1.2 on 2024-10-15 12:00

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageurl',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
    ]
