# Generated by Django 5.1.1 on 2024-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewedProduct',
            new_name='ReviewedItem',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='note',
            new_name='details',
        ),
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
